services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express_app_prod
    ports:
      - "3000:3000"
    networks:
      - app_network
    environment:
      - NODE_ENV=production
      - DB_HOST=express_app_mysql
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_DATABASE=express_app_mysql
    depends_on:
      - express_app_mysql
    restart: unless-stopped

  express_app_mysql:
    image: mysql:8.0
    container_name: express_app_mysql
    hostname: express_app_mysql
    ports:
      - "3301:3306"
    networks:
      - app_network
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_logs:/var/log/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=express_app_mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

networks:
  app_network:
    name: app_network
    driver: bridge

volumes:
  mysql_data:
    driver: local
  mysql_logs:
    driver: local